### ISSUE TITLE
What to title the book

### ISSUE THREAD

**Issue by chrisvwx** [JuliaIntro/JuliaIntroBR.jl#3]
I propose to simply translate "Introduction to Programming in Julia" into Portuguese and use this as the title.  The title "ThinkJulia" didn't work well for the [Spanish version](https://github.com/JuliaIntro/IntroAJulia.jl/issues/1).

**Comment by chrisvwx** [comment]
In PR #15 which changes the name of the package  @abelsiqueira says
> Perhaps we should use the name "Pense em Julia" in accordance with "Pense em Python": https://penseallen.github.io/PensePython2e/

Because of my experience with the Spanish version, I was going for something like "Introdução à programação em Julia", yet if "Pense em Julia: ...." works in Portuguese, then let's go for that

**Comment by abelsiqueira** [comment]
I don't personally like "Pense em ...", but since the Python translation followed it, I think it's best to follow as well, since it automatically brings the book to mind.

**Comment by chrisvwx** [comment]
So the brand "Pense em Python" is so strong that it overcomes your dislike for "Pense em Julia"?     Is Pense em Python a popular book in Brazil?

I had hoped that eventually we would have versions of the book in Spanish, Portuguese, and hopefully other languages served from the same site (say JuliaIntro.org). But if they have different titles, then it doesn't make as much sense.

**Comment by abelsiqueira** [comment]
> So the brand "Pense em Python" is so strong that it overcomes your dislike for "Pense em Julia"? Is Pense em Python a popular book in Brazil?

Yes, in essence. I have recommended ThinkJulia in the past and have been recommended ThinkPython, so it's sufficiently well known.

> I had hoped that eventually we would have versions of the book in Spanish, Portuguese, and hopefully other languages served from the same site (say JuliaIntro.org). But if they have different titles, then it doesn't make as much sense.

I was hoping for something like that too, but from my experience with translations, keeping such a large project takes too much time and effort. I can see it done with the documentation of Julia if JuliaComputing decides to support it. Without a decent translation system in place, it's even harder.
Having said that, if the translations were unified to a single project, I'd recommend keeping them with ThinkJulia and maintaining the ThinkJulia name, even though it's not translated. I can say "look into ThinkJulia, there's a Portuguese translation" because Brazilians are comfortable with words in English, especially in tech.

**Comment by chrisvwx** [comment]
I asked Ben if he wanted to be more involved with the translations, and he essentially said he was busy. Even so, we should talk w him again when we get closer to the end of this translation and try to get at least English, Spanish, and Portuguese together.

So if were were able to put them together, are you suggesting a title something like "ThinkJulia: Como pensar como um cientista da computação"?   (I'm using Google translate :-)   That works for me.   If we do this, do you have a preference for the name of the Julia package?

**Comment by abelsiqueira** [comment]
Yes, I think the title works. Regarding the package title, I guess we can use the one in the PR until we really decide what to do. Perhaps it would be better if we had a single actual installable package (the original ThinkJulia.jl being the obvious choice) and the other translations use that code. I'm not sure if this is feasible, though because the code inside the book needs to be the same.

**Comment by chrisvwx** [comment]
I like the idea of a single package (ThinkJulia.jl), and don't think it's especially tough. The code that is in the .asciidoc files can be language-specific, and when it refers to functions defined in the package, they are typically named different things.   

Even so, merging the packages together seems to me to be a separate project from this translation.

**Comment by abelsiqueira** [comment]
I've used the title Introduction to Programming in Julia translated in portuguese. If we decide to join the books, I think this can be discussed again. This can be closed.

**Comment by chrisvwx** [comment]
Great!
